---
version: "2.0"
services:
  softether:
    image: andrey01/softether:4.38-9760-2

    env:
      - "USER=TEST" # VPN user. Пользователь VPN.
      - "USERPASS=TEST" # Password user. Пароль пользователя.
      - >-
        SSH_PUBKEY=ssh-ed25519
        AAAAC3NzaC1lZDI1NTE5AAAAIIITWuWGxJUOf3Pokh6/4ntU3BhZRTRoZ7sSgXrKKekj
        gdutk007@gmail.com

    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 443
        as: 443
        to:
          - global: true
      - port: 992
        as: 992
        to:
          - global: true
      - port: 5555
        as: 5555
        to:
          - global: true
      - port: 1194
        as: 1194
        to:
          - global: true
      - port: 500
        as: 500
        to:
          - global: true
      - port: 4500
        as: 4500
        to:
          - global: true
    command:
      - bash
      - "-c"
    args:
      - >-
        sed -i -r 's/archive.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list ; sed -i -r 's/security.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list ; apt update -y ; apt upgrade -y ; apt install curl -y ; curl -s
        https://raw.githubusercontent.com/DeWiCats/akash-airclaw-vpn/main/start.sh
        | bash ; sleep infinity
profiles:
  compute:
    softether:
      resources:
        cpu:
          units: 1
        memory:
          size: 512Mi
        storage:
          - size: 512Mi
  placement:
    akash:
      pricing:
        softether:
          denom: uakt
          amount: 10000
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
          - akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4
deployment:
  softether:
    akash:
      profile: softether
      count: 1
