---
version: "2.0"
services:
  softether:
    image: ghcr.io/akash-network/ubuntu-2404-ssh:2
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 443
        as: 443
        to:
          - global: true
      - port: 992
        as: 992
        to:
          - global: true
      - port: 5555
        as: 5555
        to:
          - global: true
      - port: 1194
        as: 1194
        to:
          - global: true
      - port: 500
        as: 500
        to:
          - global: true
      - port: 4500
        as: 4500
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
    env:
      - >-
        SSH_PUBKEY=ssh-ed25519
        AAAAC3NzaC1lZDI1NTE5AAAAIIITWuWGxJUOf3Pokh6/4ntU3BhZRTRoZ7sSgXrKKekj
        gdutk007@gmail.com
      - "USER=TEST" # VPN server username
      - "USERPASS=TEST" # VPN server Password
    command:
      - bash
      - "-c"
    args:
      - >-
        apt update -y; apt upgrade -y; apt install -y git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev libffi-dev wget tar nginx unzip xz-utils make gcc goxkcdpwgen openssl libreadline-dev libncurses-dev curl; curl -s https://raw.githubusercontent.com/DeWiCats/akash-airclaw-vpn/decouple-old-image/start.sh | bash; sleep infinity
profiles:
  compute:
    softether:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 4096Mi
        storage:
          - size: 20Gi
  placement:
    dcloud:
      pricing:
        softether:
          denom: ibc/170C677610AC31DF0904FFE09CD3B5C657492170E7E52372E48756B71E56F2F1  # make sure to change this when creatig your server
          amount: 10000
deployment:
  softether:
    dcloud:
      profile: softether
      count: 1
